name: 'Training Drupal Development'
package: 'Training'
type: module
core_version_requirement: ^9 || ^10 || ^11
description: 'Training on the basics of Drupal development'
libraries:
  - training/global
